const cfg=window.DOWNLOAD_PORTAL_CONFIG??{};const authCfg=cfg.auth??{};const $=id=>document.getElementById(id);const pendingKey="listing-studio-pending-signup-email";const cooldownKey="listing-studio-signup-resend-next-at";const cooldownMs=60000;let client=null;let pendingPassword="";let timer=null;const modalLayer=$("modalLayer"),modalKicker=$("modalKicker"),modalTitle=$("modalTitle"),modalBody=$("modalBody"),emailInput=$("emailInput"),toast=$("toast");
function toastMsg(t){if(!toast)return;toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)}
function openModal(k,t){modalBody.replaceChildren();modalKicker.textContent=k;modalTitle.textContent=t;modalLayer.hidden=false}
function redirectUrl(){return new URL("/download/",location.origin).toString()}
async function supabase(){if(client)return client;if(!authCfg.supabaseUrl||!authCfg.supabaseAnonKey)return null;const{createClient}=await import("https://esm.sh/@supabase/supabase-js@2");client=createClient(authCfg.supabaseUrl,authCfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return client}
function field(label,type,autocomplete,value=""){const w=document.createElement("label");w.className="onboarding-field";const s=document.createElement("span");s.textContent=label;const i=document.createElement("input");i.type=type;i.autocomplete=autocomplete;i.value=value;w.append(s,i);return{wrapper:w,input:i}}
function status(){const p=document.createElement("p");p.className="onboarding-status registration-inline-status";p.dataset.state="neutral";return p}
function setStatus(n,t,s="neutral"){n.textContent=t;n.dataset.state=s}
function progress(active,done){const root=document.createElement("div");root.className="registration-progress";[["01","创建账号"],["02","验证邮箱"],["03","管理员开通"]].forEach(([n,l],idx)=>{const step=idx+1;const d=document.createElement("div");d.className="registration-progress-step";d.dataset.state=step<=done?"done":step===active?"active":"pending";const a=document.createElement("span");a.textContent=step<=done?"✓":n;const b=document.createElement("strong");b.textContent=l;d.append(a,b);root.appendChild(d)});modalBody.appendChild(root)}
function hero(symbol,over,title,copy){const h=document.createElement("section");h.className="registration-state-hero";const icon=document.createElement("div");icon.className="registration-state-icon";icon.textContent=symbol;const body=document.createElement("div");const o=document.createElement("span");o.className="registration-state-overline";o.textContent=over;const t=document.createElement("h3");t.textContent=title;const p=document.createElement("p");p.textContent=copy;body.append(o,t,p);h.append(icon,body);modalBody.appendChild(h)}
function emailChip(address){const d=document.createElement("div");d.className="registration-email-chip";const s=document.createElement("span");s.textContent="验证邮箱";const b=document.createElement("strong");b.textContent=address;d.append(s,b);modalBody.appendChild(d)}
function button(text,cls){const b=document.createElement("button");b.type="button";b.className=cls;b.textContent=text;return b}
function nextAt(){return Number(localStorage.getItem(cooldownKey)||0)||0}function seconds(){return Math.max(0,Math.ceil((nextAt()-Date.now())/1000))}function startCooldown(){localStorage.setItem(cooldownKey,String(Date.now()+cooldownMs))}
function syncResend(b){clearInterval(timer);const render=()=>{const s=seconds();if(s>0){b.disabled=true;b.textContent=`重新发送 (${s}s)`}else{b.disabled=false;b.textContent="重新发送验证邮件";clearInterval(timer);timer=null}};render();if(seconds()>0)timer=setInterval(render,1000)}
function renderWaiting(address){openModal("VERIFY EMAIL","验证你的邮箱");hero("✉","EMAIL SENT","验证邮件已发送","账号已经创建。请打开最新一封 Listing Studio 邮件完成邮箱验证，然后回到这里继续。");emailChip(address);progress(2,1);const note=document.createElement("div");note.className="registration-state-note";note.innerHTML="<strong>下一步</strong><span>邮箱验证完成后，账号会进入等待管理员开通权限状态。开通前不能下载或运行正式安装版。</span>";modalBody.appendChild(note);const st=status();setStatus(st,"等待邮箱验证。","neutral");modalBody.appendChild(st);const actions=document.createElement("div");actions.className="registration-state-actions";const check=button("我已完成邮箱验证","registration-primary-action");const resend=button("重新发送验证邮件","registration-secondary-action");actions.append(check,resend);modalBody.appendChild(actions);const change=button("更换邮箱重新注册","registration-text-action");modalBody.appendChild(change);syncResend(resend);
check.onclick=async()=>{const sb=await supabase();if(!sb)return setStatus(st,"账号服务还没准备好。","error");check.disabled=true;check.textContent="正在检查…";setStatus(st,"正在确认邮箱验证状态…");try{const{data:userData}=await sb.auth.getUser();const u=userData?.user;if(u&&(u.email_confirmed_at||u.confirmed_at)&&String(u.email||"").toLowerCase()===address.toLowerCase())return renderApproval(address);if(pendingPassword){const{data,error}=await sb.auth.signInWithPassword({email:address,password:pendingPassword});if(!error&&data?.user)return renderApproval(address);const m=String(error?.message||"");setStatus(st,/confirm/i.test(m)?"还没有检测到邮箱验证完成，请先打开验证邮件。":"暂未检测到验证完成。完成邮件验证后再点一次。","warn")}else setStatus(st,"完成邮件验证后返回此页面；验证链接打开的新页面也会自动识别。","warn")}catch(e){console.error(e);setStatus(st,"暂时无法检查验证状态，请稍后再试。","error")}finally{check.disabled=false;check.textContent="我已完成邮箱验证"}};
resend.onclick=async()=>{if(seconds()>0)return syncResend(resend);const sb=await supabase();if(!sb)return setStatus(st,"账号服务还没准备好。","error");resend.disabled=true;resend.textContent="发送中…";try{const{error}=await sb.auth.resend({type:"signup",email:address,options:{emailRedirectTo:redirectUrl()}});if(error)throw error;startCooldown();syncResend(resend);setStatus(st,"新的验证邮件已发送，请以最新一封为准。","ok");toastMsg("验证邮件已重新发送")}catch(e){const m=String(e?.message||"");if(Number(e?.status||0)===429||/rate limit|too many|security purposes/i.test(m)){startCooldown();syncResend(resend);setStatus(st,"发送太频繁，请等待倒计时结束后再试。","warn")}else{resend.disabled=false;resend.textContent="重新发送验证邮件";setStatus(st,"验证邮件发送失败，请稍后再试。","error")}}};
change.onclick=()=>{localStorage.removeItem(pendingKey);localStorage.removeItem(cooldownKey);pendingPassword="";openForm(address)}}
function renderApproval(address){localStorage.setItem(pendingKey,address);openModal("ACCOUNT CREATED","等待权限开通");hero("✓","EMAIL VERIFIED","邮箱验证完成","登录身份已经确认。现在只剩管理员开通软件权限，开通后即可下载、启动和接收正式更新。");emailChip(address);progress(3,2);const card=document.createElement("div");card.className="registration-approval-card";card.innerHTML="<span>SOFTWARE ACCESS</span><strong>等待管理员开通</strong><p>注册完成不会自动获得软件权限。管理员开通后，同一账号可用于网页下载和 Listing Studio 正式安装版登录。</p>";modalBody.appendChild(card);const actions=document.createElement("div");actions.className="registration-state-actions single";const enter=button("返回下载页面","registration-primary-action");actions.appendChild(enter);modalBody.appendChild(actions);enter.onclick=()=>{localStorage.removeItem(pendingKey);localStorage.removeItem(cooldownKey);pendingPassword="";location.reload()}}
function openForm(prefill=""){openModal("CREATE ACCOUNT","注册账号");const intro=document.createElement("p");intro.className="modal-summary";intro.textContent="创建登录账号后，需要先完成邮箱验证，再等待管理员开通软件权限。";modalBody.appendChild(intro);progress(1,0);const form=document.createElement("form");form.className="onboarding-form";const email=field("邮箱","email","email",prefill||emailInput?.value.trim()||"");const pass=field("设置密码","password","new-password");const confirm=field("确认密码","password","new-password");const submit=document.createElement("button");submit.className="onboarding-submit";submit.type="submit";submit.textContent="创建账号";const st=status();form.append(email.wrapper,pass.wrapper,confirm.wrapper,submit,st);modalBody.appendChild(form);const policy=document.createElement("p");policy.className="onboarding-policy";policy.textContent="注册只创建登录身份，不会自动授予软件下载权限。普通账号默认最多激活 2 台设备。";modalBody.appendChild(policy);
form.onsubmit=async e=>{e.preventDefault();const sb=await supabase();if(!sb)return setStatus(st,"账号服务还没准备好。","error");const address=email.input.value.trim(),password=pass.input.value;if(!address||!password)return setStatus(st,"请填写邮箱和密码。","error");if(password.length<8)return setStatus(st,"密码至少 8 位。","error");if(password!==confirm.input.value)return setStatus(st,"两次输入的密码不一致。","error");submit.disabled=true;submit.textContent="正在创建…";setStatus(st,"正在创建账号并发送验证邮件…");try{const{data,error}=await sb.auth.signUp({email:address,password,options:{emailRedirectTo:redirectUrl()}});if(error)throw error;if(Array.isArray(data?.user?.identities)&&data.user.identities.length===0){setStatus(st,"这个邮箱可能已经注册，可以直接登录或使用“忘记密码”。","warn");return}pendingPassword=password;localStorage.setItem(pendingKey,address);startCooldown();pass.input.value="";confirm.input.value="";if(data?.session){renderApproval(address);toastMsg("账号已创建")}else{renderWaiting(address);toastMsg("验证邮件已发送")}}catch(err){const m=String(err?.message||"");if(/already|registered|exists/i.test(m))setStatus(st,"这个邮箱可能已经注册，可以直接登录或使用“忘记密码”。","warn");else if(Number(err?.status||0)===429||/rate limit|too many/i.test(m))setStatus(st,"注册邮件发送太频繁，请稍后再试。","warn");else setStatus(st,"暂时无法创建账号，请稍后再试。","error")}finally{submit.disabled=false;submit.textContent="创建账号"}};setTimeout(()=>email.input.focus(),0)}
async function restore(){const pending=(localStorage.getItem(pendingKey)||"").trim();if(!pending)return;try{const sb=await supabase();if(!sb)return;const{data}=await sb.auth.getUser();const u=data?.user;if(u&&(u.email_confirmed_at||u.confirmed_at)&&String(u.email||"").toLowerCase()===pending.toLowerCase())renderApproval(pending)}catch{}}
const old=$("registerAction");if(old){const fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.addEventListener("click",()=>openForm())}void restore();